/* Generated by MyraPad at 6/05/2020 6:00:48 PM */

using Myra.Graphics2D.UI;

namespace SpaceMobaClient.GamePlay.Gui
{
	public partial class InGameGui
	{
		public InGameGui()
		{
			BuildUI();

            // Register event handlers
            PlayerUpgradeCloseButton.Click += 
                (s, a) => ClosePanel(PlayershipUpgradePanel);

            MotherUpgradeCloseButton.Click +=
                (s, a) => ClosePanel(MothershipUpgradePanel);
		}

        /// <summary>
        /// Closes the indicated panel.
        /// </summary>
        /// <param name="panel">Panel to close.</param>
        private void ClosePanel(Panel panel)
        {
            panel.Visible = false;
        }
	}
}