/* Generated by MyraPad at 6/05/2020 6:51:53 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace SpaceMobaClient.GamePlay.Gui
{
    partial class InGameGui : Panel
    {
        private void BuildUI()
        {
            var image1 = new Image();
            image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/minimap.png");
            image1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

            var image2 = new Image();
            image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/resources.png");
            image2.Top = -179;
            image2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

            var image3 = new Image();
            image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/ico_mothership.png");
            image3.Left = 2;
            image3.Top = -181;
            image3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

            var image4 = new Image();
            image4.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/ico_playership.png");
            image4.Left = 90;
            image4.Top = -181;
            image4.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

            var label1 = new Label();
            label1.Text = "5000";
            label1.Left = 22;
            label1.Top = -179;
            label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

            var label2 = new Label();
            label2.Text = "500";
            label2.Left = 110;
            label2.Top = -179;
            label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

            PlayerUpgradeCloseButton = new TextButton();
            PlayerUpgradeCloseButton.Text = "X";
            PlayerUpgradeCloseButton.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
            PlayerUpgradeCloseButton.PressedBackground = new SolidBrush("#474747FF");
            PlayerUpgradeCloseButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
            PlayerUpgradeCloseButton.Background = new SolidBrush("#00000000");
            PlayerUpgradeCloseButton.Id = "PlayerUpgradeCloseButton";

            var label3 = new Label();
            label3.Text = "Playership";
            label3.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");

            var horizontalSeparator1 = new HorizontalSeparator();
            horizontalSeparator1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
            horizontalSeparator1.Top = 30;

            PlayerUpgradeArmour = new MenuItem();
            PlayerUpgradeArmour.Text = "Armour";
            PlayerUpgradeArmour.Id = "PlayerUpgradeArmour";

            PlayerUpgradeSpeed = new MenuItem();
            PlayerUpgradeSpeed.Text = "Speed";
            PlayerUpgradeSpeed.Id = "PlayerUpgradeSpeed";

            PlayerUpgradeWeapon = new MenuItem();
            PlayerUpgradeWeapon.Text = "Weapon";
            PlayerUpgradeWeapon.Id = "PlayerUpgradeWeapon";

            var verticalMenu1 = new VerticalMenu();
            verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
            verticalMenu1.LabelFont = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
            verticalMenu1.Top = 39;
            verticalMenu1.Border = new SolidBrush("#00000000");
            verticalMenu1.Items.Add(PlayerUpgradeArmour);
            verticalMenu1.Items.Add(PlayerUpgradeSpeed);
            verticalMenu1.Items.Add(PlayerUpgradeWeapon);

            PlayershipUpgradePanel = new Panel();
            PlayershipUpgradePanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
            PlayershipUpgradePanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
            PlayershipUpgradePanel.Left = -200;
            PlayershipUpgradePanel.Width = 200;
            PlayershipUpgradePanel.Height = 131;
            PlayershipUpgradePanel.BorderThickness = new Thickness(3);
            PlayershipUpgradePanel.Padding = new Thickness(5);
            PlayershipUpgradePanel.Visible = false;
            PlayershipUpgradePanel.Opacity = 0.5f;
            PlayershipUpgradePanel.Background = new SolidBrush("#120045FF");
            PlayershipUpgradePanel.Border = new SolidBrush("#2B2B2BFF");
            PlayershipUpgradePanel.Id = "PlayershipUpgradePanel";
            PlayershipUpgradePanel.Widgets.Add(PlayerUpgradeCloseButton);
            PlayershipUpgradePanel.Widgets.Add(label3);
            PlayershipUpgradePanel.Widgets.Add(horizontalSeparator1);
            PlayershipUpgradePanel.Widgets.Add(verticalMenu1);

            MotherUpgradeCloseButton = new TextButton();
            MotherUpgradeCloseButton.Text = "X";
            MotherUpgradeCloseButton.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
            MotherUpgradeCloseButton.PressedBackground = new SolidBrush("#474747FF");
            MotherUpgradeCloseButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
            MotherUpgradeCloseButton.Background = new SolidBrush("#00000000");
            MotherUpgradeCloseButton.Id = "MotherUpgradeCloseButton";

            var label4 = new Label();
            label4.Text = "Mothership";
            label4.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");

            var horizontalSeparator2 = new HorizontalSeparator();
            horizontalSeparator2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
            horizontalSeparator2.Top = 30;

            MotherUpgradeArmour = new MenuItem();
            MotherUpgradeArmour.Text = "Armour";
            MotherUpgradeArmour.Id = "MotherUpgradeArmour";

            MotherUpgradeSpeed = new MenuItem();
            MotherUpgradeSpeed.Text = "Speed";
            MotherUpgradeSpeed.Id = "MotherUpgradeSpeed";

            MotherUpgradeWeapon = new MenuItem();
            MotherUpgradeWeapon.Text = "Weapon";
            MotherUpgradeWeapon.Id = "MotherUpgradeWeapon";

            var verticalMenu2 = new VerticalMenu();
            verticalMenu2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
            verticalMenu2.LabelFont = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
            verticalMenu2.Top = 39;
            verticalMenu2.Border = new SolidBrush("#00000000");
            verticalMenu2.Items.Add(MotherUpgradeArmour);
            verticalMenu2.Items.Add(MotherUpgradeSpeed);
            verticalMenu2.Items.Add(MotherUpgradeWeapon);

            MothershipUpgradePanel = new Panel();
            MothershipUpgradePanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
            MothershipUpgradePanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
            MothershipUpgradePanel.Left = -200;
            MothershipUpgradePanel.Width = 200;
            MothershipUpgradePanel.Height = 131;
            MothershipUpgradePanel.BorderThickness = new Thickness(3);
            MothershipUpgradePanel.Padding = new Thickness(5);
            MothershipUpgradePanel.Visible = false;
            MothershipUpgradePanel.Opacity = 0.5f;
            MothershipUpgradePanel.Background = new SolidBrush("#120045FF");
            MothershipUpgradePanel.Border = new SolidBrush("#2B2B2BFF");
            MothershipUpgradePanel.Id = "MothershipUpgradePanel";
            MothershipUpgradePanel.Widgets.Add(MotherUpgradeCloseButton);
            MothershipUpgradePanel.Widgets.Add(label4);
            MothershipUpgradePanel.Widgets.Add(horizontalSeparator2);
            MothershipUpgradePanel.Widgets.Add(verticalMenu2);


            Padding = new Thickness(10);
            Widgets.Add(image1);
            Widgets.Add(image2);
            Widgets.Add(image3);
            Widgets.Add(image4);
            Widgets.Add(label1);
            Widgets.Add(label2);
            Widgets.Add(PlayershipUpgradePanel);
            Widgets.Add(MothershipUpgradePanel);
        }


        public TextButton PlayerUpgradeCloseButton;
        public MenuItem PlayerUpgradeArmour;
        public MenuItem PlayerUpgradeSpeed;
        public MenuItem PlayerUpgradeWeapon;
        public Panel PlayershipUpgradePanel;
        public TextButton MotherUpgradeCloseButton;
        public MenuItem MotherUpgradeArmour;
        public MenuItem MotherUpgradeSpeed;
        public MenuItem MotherUpgradeWeapon;
        public Panel MothershipUpgradePanel;
    }
}