/* Generated by MyraPad at 16/05/2020 3:05:11 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace SpaceMobaClient.GamePlay.Gui
{
	partial class InGameGui: Panel
	{
		private void BuildUI()
		{
			FpsLabel = new Label();
			FpsLabel.Text = "20";
			FpsLabel.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
			FpsLabel.Id = "FpsLabel";

			StatusLabel = new Label();
			StatusLabel.Text = "LOW HEALTH";
			StatusLabel.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular32.fnt");
			StatusLabel.TextColor = Color.Red;
			StatusLabel.Top = 100;
			StatusLabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			StatusLabel.Visible = false;
			StatusLabel.Id = "StatusLabel";

			ArmourBar = new HorizontalProgressBar();
			ArmourBar.Value = 60;
			ArmourBar.Filler = new SolidBrush("#00FFFFFF");
			ArmourBar.BorderThickness = new Thickness(1);
			ArmourBar.Background = new SolidBrush("#00000000");
			ArmourBar.Border = new SolidBrush("#FFFFFFFF");
			ArmourBar.Id = "ArmourBar";

			HealthBar = new HorizontalProgressBar();
			HealthBar.Value = 75;
			HealthBar.Filler = new SolidBrush("#008000FF");
			HealthBar.Top = 18;
			HealthBar.BorderThickness = new Thickness(1);
			HealthBar.Background = new SolidBrush("#FF0000FF");
			HealthBar.Border = new SolidBrush("#FFFFFFFF");
			HealthBar.Id = "HealthBar";

			VitalsPanel = new Panel();
			VitalsPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VitalsPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			VitalsPanel.Top = -128;
			VitalsPanel.Width = 128;
			VitalsPanel.Height = 34;
			VitalsPanel.Padding = new Thickness(2);
			VitalsPanel.Visible = false;
			VitalsPanel.Opacity = 0.7f;
			VitalsPanel.Background = new SolidBrush("#00000000");
			VitalsPanel.Id = "VitalsPanel";
			VitalsPanel.Widgets.Add(ArmourBar);
			VitalsPanel.Widgets.Add(HealthBar);

			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/minimap.png");
			image1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			image1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			MinimapPlayerIcon = new Image();
			MinimapPlayerIcon.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/dot.png");
			MinimapPlayerIcon.Visible = false;
			MinimapPlayerIcon.Id = "MinimapPlayerIcon";

			MinimapTeamPlayer1Icon = new Image();
			MinimapTeamPlayer1Icon.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/dot.png");
			MinimapTeamPlayer1Icon.Color = Color.Green;
			MinimapTeamPlayer1Icon.Visible = false;
			MinimapTeamPlayer1Icon.Id = "MinimapTeamPlayer1Icon";

			MinimapTeamPlayer2Icon = new Image();
			MinimapTeamPlayer2Icon.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/dot.png");
			MinimapTeamPlayer2Icon.Color = Color.Green;
			MinimapTeamPlayer2Icon.Visible = false;
			MinimapTeamPlayer2Icon.Id = "MinimapTeamPlayer2Icon";

			MinimapMothershipIcon = new Image();
			MinimapMothershipIcon.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/dot.png");
			MinimapMothershipIcon.Color = Color.Aqua;
			MinimapMothershipIcon.Visible = false;
			MinimapMothershipIcon.Id = "MinimapMothershipIcon";

			MinimapPanel = new Panel();
			MinimapPanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			MinimapPanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			MinimapPanel.Width = 180;
			MinimapPanel.Id = "MinimapPanel";
			MinimapPanel.Widgets.Add(image1);
			MinimapPanel.Widgets.Add(MinimapPlayerIcon);
			MinimapPanel.Widgets.Add(MinimapTeamPlayer1Icon);
			MinimapPanel.Widgets.Add(MinimapTeamPlayer2Icon);
			MinimapPanel.Widgets.Add(MinimapMothershipIcon);

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/resources.png");
			image2.Top = -179;
			image2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/ico_mothership.png");
			image3.Left = 2;
			image3.Top = -181;
			image3.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			var image4 = new Image();
			image4.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("Content/Gui/ico_playership.png");
			image4.Left = 90;
			image4.Top = -181;
			image4.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			ResourcesMothershipLabel = new Label();
			ResourcesMothershipLabel.Text = "5000";
			ResourcesMothershipLabel.Left = 22;
			ResourcesMothershipLabel.Top = -179;
			ResourcesMothershipLabel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			ResourcesMothershipLabel.Id = "ResourcesMothershipLabel";

			ResourcesPlayershipLabel = new Label();
			ResourcesPlayershipLabel.Text = "500";
			ResourcesPlayershipLabel.Left = 110;
			ResourcesPlayershipLabel.Top = -179;
			ResourcesPlayershipLabel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			ResourcesPlayershipLabel.Id = "ResourcesPlayershipLabel";

			PlayerUpgradeCloseButton = new TextButton();
			PlayerUpgradeCloseButton.Text = "X";
			PlayerUpgradeCloseButton.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
			PlayerUpgradeCloseButton.PressedBackground = new SolidBrush("#474747FF");
			PlayerUpgradeCloseButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			PlayerUpgradeCloseButton.Background = new SolidBrush("#00000000");
			PlayerUpgradeCloseButton.Id = "PlayerUpgradeCloseButton";

			var label1 = new Label();
			label1.Text = "Playership";
			label1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");

			var horizontalSeparator1 = new HorizontalSeparator();
			horizontalSeparator1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			horizontalSeparator1.Top = 30;

			PlayerUpgradeArmour = new MenuItem();
			PlayerUpgradeArmour.Text = "Armour";
			PlayerUpgradeArmour.Id = "PlayerUpgradeArmour";

			PlayerUpgradeSpeed = new MenuItem();
			PlayerUpgradeSpeed.Text = "Speed";
			PlayerUpgradeSpeed.Id = "PlayerUpgradeSpeed";

			PlayerUpgradeWeapon = new MenuItem();
			PlayerUpgradeWeapon.Text = "Weapon";
			PlayerUpgradeWeapon.Id = "PlayerUpgradeWeapon";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			verticalMenu1.LabelFont = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
			verticalMenu1.Top = 39;
			verticalMenu1.Border = new SolidBrush("#00000000");
			verticalMenu1.Items.Add(PlayerUpgradeArmour);
			verticalMenu1.Items.Add(PlayerUpgradeSpeed);
			verticalMenu1.Items.Add(PlayerUpgradeWeapon);

			PlayershipUpgradePanel = new Panel();
			PlayershipUpgradePanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			PlayershipUpgradePanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			PlayershipUpgradePanel.Left = -250;
			PlayershipUpgradePanel.Width = 200;
			PlayershipUpgradePanel.Height = 131;
			PlayershipUpgradePanel.BorderThickness = new Thickness(3);
			PlayershipUpgradePanel.Padding = new Thickness(5);
			PlayershipUpgradePanel.Visible = false;
			PlayershipUpgradePanel.Opacity = 0.5f;
			PlayershipUpgradePanel.Background = new SolidBrush("#120045FF");
			PlayershipUpgradePanel.Border = new SolidBrush("#2B2B2BFF");
			PlayershipUpgradePanel.Id = "PlayershipUpgradePanel";
			PlayershipUpgradePanel.Widgets.Add(PlayerUpgradeCloseButton);
			PlayershipUpgradePanel.Widgets.Add(label1);
			PlayershipUpgradePanel.Widgets.Add(horizontalSeparator1);
			PlayershipUpgradePanel.Widgets.Add(verticalMenu1);

			MotherUpgradeCloseButton = new TextButton();
			MotherUpgradeCloseButton.Text = "X";
			MotherUpgradeCloseButton.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
			MotherUpgradeCloseButton.PressedBackground = new SolidBrush("#474747FF");
			MotherUpgradeCloseButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			MotherUpgradeCloseButton.Background = new SolidBrush("#00000000");
			MotherUpgradeCloseButton.Id = "MotherUpgradeCloseButton";

			var label2 = new Label();
			label2.Text = "Mothership";
			label2.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");

			var horizontalSeparator2 = new HorizontalSeparator();
			horizontalSeparator2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			horizontalSeparator2.Top = 30;

			MotherUpgradeArmour = new MenuItem();
			MotherUpgradeArmour.Text = "Armour";
			MotherUpgradeArmour.Id = "MotherUpgradeArmour";

			MotherUpgradeSpeed = new MenuItem();
			MotherUpgradeSpeed.Text = "Speed";
			MotherUpgradeSpeed.Id = "MotherUpgradeSpeed";

			MotherUpgradeWeapon = new MenuItem();
			MotherUpgradeWeapon.Text = "Weapon";
			MotherUpgradeWeapon.Id = "MotherUpgradeWeapon";

			var verticalMenu2 = new VerticalMenu();
			verticalMenu2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			verticalMenu2.LabelFont = MyraEnvironment.DefaultAssetManager.Load<SpriteFont>("Content/Fonts/Iceberg-Regular24.fnt");
			verticalMenu2.Top = 39;
			verticalMenu2.Border = new SolidBrush("#00000000");
			verticalMenu2.Items.Add(MotherUpgradeArmour);
			verticalMenu2.Items.Add(MotherUpgradeSpeed);
			verticalMenu2.Items.Add(MotherUpgradeWeapon);

			MothershipUpgradePanel = new Panel();
			MothershipUpgradePanel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			MothershipUpgradePanel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			MothershipUpgradePanel.Left = -250;
			MothershipUpgradePanel.Width = 200;
			MothershipUpgradePanel.Height = 131;
			MothershipUpgradePanel.BorderThickness = new Thickness(3);
			MothershipUpgradePanel.Padding = new Thickness(5);
			MothershipUpgradePanel.Visible = false;
			MothershipUpgradePanel.Opacity = 0.5f;
			MothershipUpgradePanel.Background = new SolidBrush("#120045FF");
			MothershipUpgradePanel.Border = new SolidBrush("#2B2B2BFF");
			MothershipUpgradePanel.Id = "MothershipUpgradePanel";
			MothershipUpgradePanel.Widgets.Add(MotherUpgradeCloseButton);
			MothershipUpgradePanel.Widgets.Add(label2);
			MothershipUpgradePanel.Widgets.Add(horizontalSeparator2);
			MothershipUpgradePanel.Widgets.Add(verticalMenu2);

			
			Padding = new Thickness(10);
			Widgets.Add(FpsLabel);
			Widgets.Add(StatusLabel);
			Widgets.Add(VitalsPanel);
			Widgets.Add(MinimapPanel);
			Widgets.Add(image2);
			Widgets.Add(image3);
			Widgets.Add(image4);
			Widgets.Add(ResourcesMothershipLabel);
			Widgets.Add(ResourcesPlayershipLabel);
			Widgets.Add(PlayershipUpgradePanel);
			Widgets.Add(MothershipUpgradePanel);
		}

		
		public Label FpsLabel;
		public Label StatusLabel;
		public HorizontalProgressBar ArmourBar;
		public HorizontalProgressBar HealthBar;
		public Panel VitalsPanel;
		public Image MinimapPlayerIcon;
		public Image MinimapTeamPlayer1Icon;
		public Image MinimapTeamPlayer2Icon;
		public Image MinimapMothershipIcon;
		public Panel MinimapPanel;
		public Label ResourcesMothershipLabel;
		public Label ResourcesPlayershipLabel;
		public TextButton PlayerUpgradeCloseButton;
		public MenuItem PlayerUpgradeArmour;
		public MenuItem PlayerUpgradeSpeed;
		public MenuItem PlayerUpgradeWeapon;
		public Panel PlayershipUpgradePanel;
		public TextButton MotherUpgradeCloseButton;
		public MenuItem MotherUpgradeArmour;
		public MenuItem MotherUpgradeSpeed;
		public MenuItem MotherUpgradeWeapon;
		public Panel MothershipUpgradePanel;
	}
}