/* Generated by MyraPad at 6/05/2020 4:42:55 PM */
using System;

using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

using SpaceMobaClient.Systems.Scenes;

namespace SpaceMobaClient.GamePlay.Gui
{
	partial class LoginMenuGui: Grid
	{
        TextButton LoginButton;

		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Blackhole";
			label1.Font = GameClient.GetGameClient().Content.Load<SpriteFont>("Fonts/Iceberg32");
			label1.DisabledTextColor = Color.White;
			label1.OverTextColor = new Color
			{
				B = 255,
				G = 255,
				R = 255,
				A = 0,
			};
			label1.Margin = new Thickness(0, 20, 0, 0);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label1.OverBackground = new SolidBrush("#00000000");

			var textBox1 = new TextBox();
			textBox1.Text = "Username";
			textBox1.Font = GameClient.GetGameClient().Content.Load<SpriteFont>("Fonts/Iceberg24");
            textBox1.TextVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			textBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox1.Width = 200;
			textBox1.Height = 40;
			textBox1.Background = new SolidBrush("#1C1C1CFF");

			var textBox2 = new TextBox();
			textBox2.Text = "Password";
			textBox2.Font = GameClient.GetGameClient().Content.Load<SpriteFont>("Fonts/Iceberg24");
            textBox2.PasswordField = true;
			textBox2.TextVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			textBox2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox2.Width = 200;
			textBox2.Height = 40;
			textBox2.Margin = new Thickness(0, 45, 0, 0);
			textBox2.GridRow = 1;
			textBox2.Background = new SolidBrush("#1C1C1FFF");

			LoginButton = new TextButton();
            LoginButton.Text = "Login";
            LoginButton.Font = GameClient.GetGameClient().Content.Load<SpriteFont>("Fonts/Iceberg24");
            LoginButton.Width = 200;
            LoginButton.Height = 40;
            LoginButton.Margin = new Thickness(0, 90, 0, 0);
            LoginButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
            LoginButton.GridRow = 2;

			var panel1 = new Panel();
			panel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			panel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			panel1.Margin = new Thickness(0, 50, 0, 0);
			panel1.BorderThickness = new Thickness(1);
			panel1.Padding = new Thickness(20);
			panel1.GridColumn = 1;
			panel1.Background = new SolidBrush("#000000FF");
			panel1.Border = new SolidBrush("#FFFFFFFF");
			panel1.Widgets.Add(textBox1);
			panel1.Widgets.Add(textBox2);
			panel1.Widgets.Add(LoginButton);

			var panel2 = new Panel();
			panel2.BorderThickness = new Thickness(2);
			panel2.GridColumn = 1;
			panel2.GridRow = 1;
			panel2.Background = new SolidBrush("#0F002DFF");
			panel2.Border = new SolidBrush("#FFFFFFFF");
			panel2.Widgets.Add(label1);
			panel2.Widgets.Add(panel1);

			
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 400,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 300,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(panel2);
		}

		
	}
}